#!/usr/bin/env bash

go clean -testcache

echo "Running all unit tests"

go test --coverprofile=coverage.out -count=1 -p 1 -cover ./...
if [ $? -eq 1 ]; then
    echo "Failed tests"
    exit 1
fi

./dev-bin/analyse ./coverage.out